CREATE TABLE `users` (
  `user_id` CHAR(36) NOT NULL DEFAULT (uuid()),
  `name` VARCHAR(100) NOT NULL,
  `is_guest` TINYINT(1) DEFAULT '0',
  `email` VARCHAR(100) UNIQUE NOT NULL,
  `phone` VARCHAR(20) DEFAULT NULL,
  `nic_no` VARCHAR(20) UNIQUE NOT NULL,
  `nic_dl_photo` VARCHAR(255) DEFAULT NULL,
  `username` VARCHAR(50) UNIQUE NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;